---
- hosts: all

  vars:
    home: "{{ lookup('env','HOME') }}"
  vars_files:
    - macSoftware.yaml
    
  tasks:  
    - name: macSetup repository already exist ?
      git: repo=https://github.com/bhdicaire/macSetup.git dest=/tmp/macSetup clone=no update=no

#    - name: Copy setup
#      git: repo=https://github.com/bhdicaire/macSetup.git dest=/tmp/macSetup state=present

    - name: Setup {{ home }} sub directories
      file: path='{{ home }}{{ item }}' state=directory owner=bhdicaire group=staff mode=0751
      with_items:
        - "/bin/"
        - "/.gitconfig/"
    - file: path='{{ home }}/.ssh/' state=directory mode=0700

    - name: Copy opiniated bash, color palettes, git and services configuration
      copy: src='/tmp/macSetup/bin/' dest='{{ home }}/bin/' mode=0751 directory_mode=yes

    - copy: src='{{ item.src }}' dest='{{ item.dest }}' mode=651
      with_items:       
        - { src: '/tmp/macSetup/colors/', dest: '{{ home }}/Library/Colors/' }
        - { src: '/tmp/macSetup/services/', dest: '{{ home }}//Library/Services/' }
        - { src: '/tmp/macSetup/dot/', dest: '{{ home }}/' }
#        - { src: '/tmp/macSetup/gitconfig', dest: '{{ home }}/.gitconfig/' }
#        - { src: '/tmp/macSetup/ssh', dest: '{{ home }}/.ssh/' }

    - name: Update homebrew & cleanup
      homebrew: update_homebrew=yes upgrade_all=yes
    - shell: brew cleanup

    - name: Install regular applications with homebrew
      homebrew: name="{{ brew_standard }}" state=present

    - shell: brew cask cleanup

    - name: Make template
      make: chdir=/tmp/macSetup target=hello
#    become: yes