# This task will get the current launchclt settings.

# csrutil status

################################################################################
#   Information
################################################################################
  
- name: Get the current System Integrity Protection Status

  command: "csrutil status"
  register: status

- name: Raise error on status
  fail:
    msg: "The system integrity proteciton is currently enabled!"
  when: '"enabled" in status.stdout'
  
- name: Print the current status 
  debug:
    var: status
    
  ignore_errors: no
  tags:
    - debug