# Playbook to run the macsetup role
---
- name: Mac software installation (software)
  
  hosts: macsetup
  
  # Pre flight actions
  pre_tasks:
  
    - name: Display all homebrew taps used by this installation
      debug: 
        msg: "{{ brew_tap }}"
        verbosity: 1
  
    - name: Update homebrew environment   
      homebrew: update_homebrew=yes upgrade_all=yes
      
    - name: Cleanup homebrew environment  
      shell: brew cleanup
      
  # List roles
  roles:
    - { role: macsetup, brew_app: "", brew_cask: "", brew_tap: "" }
     # - { role: macsetup, tags: ["software"], brew_app: "{{ brew_app }}" }
     # - { role: macsetup, tags: ["software"], brew_app: "{{ brew_dev }}" }
  
  # Post flight actions
  post_tasks:
...