# Playbook to run the macsetup role
---
- hosts: macsetup
  
  vars:
    - do_application_install: false
  
  vars_files: 
    - vars-tests.yml
  
  roles:
    - { role: macsetup, do_security_check: true }
    #- { role: macsetup, do_sysprep: true }
    #- { role: macsetup, do_application_install: true, brew_app: "", brew_cask: "", brew_tap: "" }
    #- { role: macsetup, do_application_update: true, do_application_cleanup: true }
  
...