# Playbook to run the macsetup role
---
- hosts: macsetup
  
  vars:
    # Section Flafs:
    # role/macsetup/defaults/main.yml
    # refer to that file to define your vars-files include below.
    # these are used to activate sections of the role
    - do_application_install: false
    
    # Section variables:
    # role/macsetup/vars/main.yml
    # refer to that file to define your vars-files include below
    # these are the variables used be defaut for section's variables
    - scutil_deny_new_interfaces_on_locked_screen: True
  
  vars_files:
    # Load your setup configuration:
    - vars-tests.yml
  
  roles:
    - { role: macsetup }
...